import createNextIntlPlugin from "next-intl/plugin";

const withNextIntl = createNextIntlPlugin("./src/i18n.ts");

const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    return [
      // Eski /therapist/ → yeni tip bazlı URL (psikolog default)
      { source: "/:locale/therapist/:slug", destination: "/:locale/psikolog/:slug", permanent: true },
      // Eski /danisan/ (yanlış yazım: "danışan"=terapiye giden kişi) → doğru /psikolojik-danisman/
      { source: "/:locale/danisan/:slug", destination: "/:locale/psikolojik-danisman/:slug", permanent: true },
      // SEO T6: bozuk/keyword-stuffed slug'lar (>60 karakter, başta/sonda
      // tire, çift tire) → isim+şehir bazlı temiz slug'lara 301. Liste,
      // 2026-09-17'de Supabase'ten çekilen tam malformed-slug taramasından
      // (200 kayıt) ve mert'in elle onayladığı eşleştirmeden üretildi.
      { source: "/:locale/psikiyatrist/gaziantep-pedagog-psikolog-esma-temiz-calkilicoyun-terapistiemdr-terapisti-cocuk-ergen-yet", destination: "/:locale/psikiyatrist/esma-temiz-calkilic-gaziantep", permanent: true },
      { source: "/:locale/psikolog/-antalya-psikolog-konyaalti-cag-psikolojik-danismanlik-merkezi-uzman-psikolog-cagri-ulusoy", destination: "/:locale/psikolog/cagri-ulusoy-antalya", permanent: true },
      { source: "/:locale/psikiyatrist/f-volkan-yuksel-antalya-psikiyatrist-psikoterapist-cinsel-terapist-antalya-psikoloji-mer", destination: "/:locale/psikiyatrist/f-volkan-yuksel-antalya", permanent: true },
      { source: "/:locale/psikolog/ozge-seker-yenimahalle-psikologyetiskin-terapisien-iyi-psikologcocuk-psikologoyu", destination: "/:locale/psikolog/ozge-seker-yenimahalle-ankara", permanent: true },
      { source: "/:locale/psikolog/kim-psikoloji-rehberlik-ve-psikolojik-danismanlik-merkezi-pedagog-aile-danismani", destination: "/:locale/psikolog/kim-psikoloji-rehberlik-ve-psikolojik-danismanlik-istanbul", permanent: true },
      { source: "/:locale/psikolog/sisli-psikolog-ozne-terapi-aile-danisma-merkezi-sisli-psikolog-randevu-cocuk-psi", destination: "/:locale/psikolog/ozne-terapi-aile-danisma-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolog/kayseri-uzman-psikolog-elif-kelesoglu-kayseri-psikolog-kayseri-emdr-terapisi-kay", destination: "/:locale/psikolog/elif-kelesoglu-kayseri", permanent: true },
      { source: "/:locale/psikolog/kayseri-psikolog-serdar-avsar-kaysseri-emdr-terapisi-kayseri-butuncul-psikoterap", destination: "/:locale/psikolog/serdar-avsar-kayseri", permanent: true },
      { source: "/:locale/psikolog/ozel-akdeniz-psikoloji-aile-danisma-merkezi-mersin-psikologmersin-online-psikolo", destination: "/:locale/psikolog/ozel-akdeniz-psikoloji-aile-danisma-merkezi-mersin", permanent: true },
      { source: "/:locale/psikolog/mersin-psikolog-murat-bilim-yetiskin-bireysel-terapi-cift-terapisi-ve-ergen-psik", destination: "/:locale/psikolog/mersin-psikolog-murat-bilim", permanent: true },
      { source: "/:locale/psikolog/cansu-arslan-dagbakan-bireysel-terapi-cift-terapisi-aile-terapisi-cinsel-terapi-", destination: "/:locale/psikolog/cansu-arslan-dagbakan-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/doc-dr-selma-bozkurt-psikiyatrist-psikoterapist-mcp-donusumsel-iliski-ve-yasam-k", destination: "/:locale/psikiyatrist/selma-bozkurt-psikiyatrist-psikoterapist-mcp-istanbul", permanent: true },
      { source: "/:locale/psikolog/istanbul-sisli-klinik-psikolog-dolunay-zumrut-cetin-bireysel-terapi-iliski-depre", destination: "/:locale/psikolog/istanbul-sisli-klinik-psikolog-dolunay-zumrut", permanent: true },
      { source: "/:locale/psikolog/ali-olcay-akcay-ankara-psikologcankaya-psikolog-ergen-terapi-cift-terapi-aile-da", destination: "/:locale/psikolog/ali-olcay-akcay-ankara", permanent: true },
      { source: "/:locale/psikolog/kl-psk-serap-guneltay-emdr-terapisi-sematerapi-dinamik-psikoterapi-evlilik-ve-ci", destination: "/:locale/psikolog/serap-guneltay-istanbul", permanent: true },
      { source: "/:locale/psikolog/ankara-psikolog-uzman-psikolog-hilal-kara-yilmaz-cift-terapisi-cinsel-terapi-emd", destination: "/:locale/psikolog/ankara-uzman-psikolog-hilal-kara-yilmaz", permanent: true },
      { source: "/:locale/psikiyatrist/cankaya-santa-psikoloji-danismanlik-merkeziemdr-terapisi-oyun-terapisi-aile-ve-c", destination: "/:locale/psikiyatrist/cankaya-santa-psikoloji-danismanlik-merkezi-ankara", permanent: true },
      { source: "/:locale/psikolog/kubra-altiparmak-hamamci-antalya-psikolog-antalya-psikoloji-bireysel-danismanlik", destination: "/:locale/psikolog/kubra-altiparmak-hamamci-antalya", permanent: true },
      { source: "/:locale/psikolog/alpaslan-keskinemdrtravma-bireysel-terapibdt-dinamikaktarim-terapi-cinsel-terapi", destination: "/:locale/psikolog/alpaslan-keskin-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/loya-psikolojik-danismanlik-merkezi-emdr-moxo-dikkat-testi-bireysel-danismanlik-", destination: "/:locale/psikiyatrist/loya-psikolojik-danismanlik-merkezi-emdr-moxo-dikkat-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/ankara-psikolog-uzman-psikolog-birsen-cinar-bireysel-terapi-oyun-terapisi-cift-t", destination: "/:locale/psikiyatrist/ankara-uzman-psikolog-birsen-cinar", permanent: true },
      { source: "/:locale/psikolog/hatice-merve-camuzcu-yenimahalle-ankara-psikolog-terapist-cift-ergen-cocuk-oyun-", destination: "/:locale/psikolog/hatice-merve-camuzcu-ankara", permanent: true },
      { source: "/:locale/psikolog/konya-pedagog-ayfer-duman-psikomed-danismanlik-konya-cocuk-ve-ergen-psikoloji-me", destination: "/:locale/psikolog/ayfer-duman-konya", permanent: true },
      { source: "/:locale/psikolog/arti-enstitu-psikolojik-danismanlik-ve-dikkat-gelistirme-merkezi-mungan-egitim-v", destination: "/:locale/psikolog/arti-enstitu-psikolojik-danismanlik-ve-dikkat-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/bursa-psikiyatrist-uzm-dr-duran-tiras-psikoterapist-kumar-bagimliligi-depresyon-", destination: "/:locale/psikiyatrist/duran-tiras-bursa", permanent: true },
      { source: "/:locale/psikolog/cekmekoy-psikolog-i-klinik-psikolog-kubra-gunes-i-tasdelen-psikolog-i-sancaktepe", destination: "/:locale/psikolog/kubra-gunes-istanbul", permanent: true },
      { source: "/:locale/psikolog/abdulkadir-gungor-bakirkoy-tavsiye-edilen-psikolog-bireysel-terapi-cinsel-terapi", destination: "/:locale/psikolog/abdulkadir-gungor-istanbul", permanent: true },
      { source: "/:locale/psikolog/psikoterapi-atolyesi-atasehir-psikolog-cift-terapisi-emdr-terapi-oyun-terapisi-c", destination: "/:locale/psikolog/psikoterapi-atolyesi-istanbul", permanent: true },
      { source: "/:locale/psikolog/irade-psikolojik-danismanlik-umraniye-yuz-yuzeonline-terapi-coklu-kimlik-bozuklu", destination: "/:locale/psikolog/irade-psikolojik-danismanlik-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/prof-dr-hakan-kumbasar-cankaya-panik-bozukluk-psikoterapist-depresyon-ruh-saglig", destination: "/:locale/psikiyatrist/hakan-kumbasar-ankara", permanent: true },
      { source: "/:locale/psikolog/cekmekoy-klinik-psikolog-pelin-aslan-ozturk-cekmekoy-psikolog-tasdelen-psikolog-", destination: "/:locale/psikolog/pelin-aslan-ozturk-istanbul", permanent: true },
      { source: "/:locale/psikolog/pozitif-psikoloji-enstitisu-bakirkoy-psikolog-bakirkoy-cift-terapisi-bakirkoy-ai", destination: "/:locale/psikolog/abdurrahman-kendirci-istanbul", permanent: true },
      { source: "/:locale/psikolog/izmir-psikolog-bagimlilik-cift-aile-cocuk-yetiskin-ergen-klinik-psikolog-danisma", destination: "/:locale/psikolog/izmir-psikolog-izmir", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-selin-ayse-ipek-bas-antalya-cocuk-ve-genc-psikiyatrisi-uzmani-psikoterapi", destination: "/:locale/psikiyatrist/selin-ayse-ipek-bas-antalya", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-perihan-turhan-gurbuz-antalya-cocuk-psikiyatrisi-antalya-ergen-psikiyatri", destination: "/:locale/psikiyatrist/perihan-turhan-gurbuz-antalya", permanent: true },
      { source: "/:locale/psikolog/tugba-sargin-cift-terapisi-aile-terapisti-online-goruntulu-gorusme-bireysel-tera", destination: "/:locale/psikolog/tugba-sargin-eskisehir", permanent: true },
      { source: "/:locale/psikolog/eskisehir-psikolog-orhan-ozturk-eskisehirde-psikolog-eskisehirde-online-psikoter", destination: "/:locale/psikolog/orhan-ozturk-eskisehirde-eskisehir", permanent: true },
      { source: "/:locale/psikolojik-danisman/dilek-uzkara-kayseri-melikgazi-psikolojik-danisman-ergen-yetiskin-danismanligi-a", destination: "/:locale/psikolojik-danisman/dilek-uzkara-kayseri", permanent: true },
      { source: "/:locale/psikolog/diyarbakir-psikolog-arketip-psikoloji-uzman-klinik-psikolog-yetiskin-ergen-cocuk", destination: "/:locale/psikolog/diyarbakir-psikolog-diyarbakir", permanent: true },
      { source: "/:locale/psikolog/uzm-klinik-psikolog-mehtap-dogan-veziroglu-ay-isigi-psikoloji-ve-danismanlik-mer", destination: "/:locale/psikolog/mehtap-dogan-veziroglu-ay-isigi-sanliurfa", permanent: true },
      { source: "/:locale/psikolog/uzman-noropsikolog-nurullah-abas-sinirbilimci-psikologbeyin-gelisim-uzmani-brain", destination: "/:locale/psikolog/nurullah-abas-sanliurfa", permanent: true },
      { source: "/:locale/psikolog/zirve-rehberlik-ve-psikolojik-danisma-merkezi-samsun-psikolog-atakum-psikolog-co", destination: "/:locale/psikolog/zirve-rehberlik-samsun", permanent: true },
      { source: "/:locale/psikolog/samsun-psikolog-ozel-iz-aile-danisma-merkezi-samsun-psikolog-ve-psikolojik-danis", destination: "/:locale/psikolog/samsun-psikolog-ozel-iz-aile-danisma-merkezi", permanent: true },
      { source: "/:locale/psikolog/ozel-surec-psikoloji-aile-danisma-merkezi-psk-elif-akbas-psk-dan-onur-keskinsoy-", destination: "/:locale/psikolog/elif-akbas-samsun", permanent: true },
      { source: "/:locale/psikolog/denizli-imago-psikoloji-psikolojik-danisma-merkezi-denizli-psikolog-denizli-peda", destination: "/:locale/psikolog/denizli-imago-psikoloji-psikolojik-danisma-merkezi", permanent: true },
      { source: "/:locale/psikolog/uzm-klinik-psikolog-ezgi-ozgenel-denizli-psikolog-cocuk-ergen-yetiskin-ailecift-", destination: "/:locale/psikolog/ezgi-ozgenel-denizli", permanent: true },
      { source: "/:locale/psikolog/kayseri-psikolog-enes-delikus-yetiskin-psikologu-ergen-ve-cocuk-psikologu-emdr-t", destination: "/:locale/psikolog/enes-delikus-kayseri", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-asli-seda-kirac-psikiyatrist-konya-psikiyatrist-psikiyatri-doktoru-meram-", destination: "/:locale/psikiyatrist/asli-seda-kirac-konya", permanent: true },
      { source: "/:locale/psikolog/yeni-hayat-psikoloji-malatya-psikolog-bireysel-terapicift-terapisi-online-terapi", destination: "/:locale/psikolog/yeni-hayat-malatya", permanent: true },
      { source: "/:locale/psikiyatrist/psychome-psikolojik-danismanlik-malatyaonline-psikologcocuk-psikologuemdr-terapi", destination: "/:locale/psikiyatrist/psychome-psikolojik-danismanlik-malatya", permanent: true },
      { source: "/:locale/psikolog/kocaeli-psikoloji-evi-kocaeli-psikoloji-kocaeli-psikolog-cocuk-ergen-yetiskin-da", destination: "/:locale/psikolog/kocaeli-psikoloji-evi", permanent: true },
      { source: "/:locale/psikolog/aleyna-avci-kocaeli-psikolog-uzman-klinik-psikolog-izmit-psikolog-yetiskin-terap", destination: "/:locale/psikolog/aleyna-avci-kocaeli", permanent: true },
      { source: "/:locale/psikolog/uzm-klinik-psikolog-leyla-kilic-psikoloji-klinigi-kocaeli-psikolog-uzm-klinik-ps", destination: "/:locale/psikolog/leyla-kilic-kocaeli", permanent: true },
      { source: "/:locale/psikolog/kocaeli-psikolog-sayara-askar-kocaeli-oyun-terapisibireysel-terapiergen-terapici", destination: "/:locale/psikolog/sayara-askar-kocaeli", permanent: true },
      { source: "/:locale/psikolog/psikoeren-psikolog-ofisi-kocaeli-izmit-psikologizmit-psikolog-randevuonline-psik", destination: "/:locale/psikolog/psikoeren-psikolog-ofisi-kocaeli", permanent: true },
      { source: "/:locale/psikolog/izmit-klinik-psikolog-gizem-dogrubireysel-terapiyetiskin-terapisionline-terapide", destination: "/:locale/psikolog/gizem-dogru-kocaeli", permanent: true },
      { source: "/:locale/psikolog/selin-kahvecioglu-ocak-birey-cift-ve-aile-terapisti-bdt-emdr-kadikoy-psikolog-on", destination: "/:locale/psikolog/selin-kahvecioglu-ocak-istanbul", permanent: true },
      { source: "/:locale/psikolog/sakarya-psikolog-aile-danismani-beyza-kuzhan-adamental-psikolojik-danismanlik-me", destination: "/:locale/psikolog/beyza-kuzhan-adamental-sakarya", permanent: true },
      { source: "/:locale/psikolog/uzman-psikolojik-danisman-alpaslan-alpaslan-lumenis-psikolojik-danismanlik-merke", destination: "/:locale/psikolog/alpaslan-alpaslan-lumenis-sakarya", permanent: true },
      { source: "/:locale/psikolog/dan-zeynep-yalin-psikolojik-danisman-aile-danismani-egitim-danismani-cocuk-ergen", destination: "/:locale/psikolog/zeynep-yalin-sakarya", permanent: true },
      { source: "/:locale/psikolog/gul-billur-gencer-acikel-kucukcekmece-psikolog-emdr-travma-terapisi-ergen-yetisk", destination: "/:locale/psikolog/gul-billur-gencer-acikel-istanbul", permanent: true },
      { source: "/:locale/psikolog/uzm-klinik-psikolog-fatih-kirisci-kmaras-ergenyetiskincift-ve-aile-terapisi-ista", destination: "/:locale/psikolog/fatih-kirisci-kahramanmaras", permanent: true },
      { source: "/:locale/psikiyatrist/kahramanmaras-ala-ark-grup-danismanlik-emdr-cift-yetiskin-ergen-ve-oyun-danisman", destination: "/:locale/psikiyatrist/ala-ark-kahramanmaras", permanent: true },
      { source: "/:locale/psikiyatrist/ali-demir-kahramanmaras-psikolog-emdr-btd-cocuk-ergen-terapisi-cift-terapisi-cin", destination: "/:locale/psikiyatrist/ali-demir-kahramanmaras", permanent: true },
      { source: "/:locale/psikolog/eyup-durmaz-sisli-aile-terapi-nisantasi-psikolog-nisantasi-psikolog-onerisi-sisl", destination: "/:locale/psikolog/eyup-durmaz-psikolog-istanbul", permanent: true },
      { source: "/:locale/psikolog/eyup-durmaz-aile-cift-ve-cinsel-terapist-bakirkoy-psikoloji-bakirkoy-psikolog-on", destination: "/:locale/psikolog/eyup-durmaz-istanbul", permanent: true },
      { source: "/:locale/psikolog/busra-engin-kayseri-psikolog-kayseri-pedagog-cocuk-ve-ergen-terapisti-aile-ve-ci", destination: "/:locale/psikolog/busra-engin-kayseri", permanent: true },
      { source: "/:locale/psikolog/emdr-terapisi-cift-terapisi-klinik-psikolog-gul-colak-bagdat-caddesi-suadiye-cad", destination: "/:locale/psikolog/gul-colak-istanbul", permanent: true },
      { source: "/:locale/psikolog/gamze-kose-emdr-terapisi-cocuk-ergen-yetiskin-cift-psikologu-wisc-4-zeka-testi-m", destination: "/:locale/psikolog/gamze-kose-istanbul", permanent: true },
      { source: "/:locale/psikolog/istanbul-psikolog-onur-cansiz-emdr-terapisi-cift-terapi-evlilik-terapisi-sema-te", destination: "/:locale/psikolog/onur-cansiz-istanbul", permanent: true },
      { source: "/:locale/psikolog/cekmekoy-tasdelen-klinik-psikolog-nur-secil-salur-metin-umraniye-psikolog-sariga", destination: "/:locale/psikolog/nur-secil-salur-metin-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/psikolojik-danisman-asli-salman-aile-cift-danismani-cocuk-ergen-yetiskin-danisma", destination: "/:locale/psikolojik-danisman/asli-salman-istanbul", permanent: true },
      { source: "/:locale/psikolog/aile-danismani-abdullah-ozer-uzman-aile-danismani-psikoterapi-cinsel-terapi-hipn", destination: "/:locale/psikolog/abdullah-ozer-izmir", permanent: true },
      { source: "/:locale/psikiyatrist/doc-dr-yunus-hacimusalar-psikiyatrist-psikoterapist-kayseri-psikiyatri-kayseri-p", destination: "/:locale/psikiyatrist/yunus-hacimusalay-kayseri", permanent: true },
      { source: "/:locale/psikolog/mine-caner-denizli-psikologdenizli-psikolog-randevuergenyetiskinonline-psikolog", destination: "/:locale/psikolog/mine-caner-denizli", permanent: true },
      { source: "/:locale/psikolog/dedio-psikoloji-atasehir-psikolog-ergen-cocuk-aile-ve-cift-psikolog-emdr-terapi", destination: "/:locale/psikolog/deniz-dogruoz-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/beylikduzu-klinik-psikolog-elif-demirci-caglar-ozel-saglik-meslek-hizmet-birimi", destination: "/:locale/psikolojik-danisman/elif-demirci-caglar-istanbul", permanent: true },
      { source: "/:locale/psikolog/by-deva-rehberlik-ve-psikolojik-danismanlik-merkezi-antalya-muratpasa-psikolog", destination: "/:locale/psikolog/by-deva-rehberlik-ve-psikolojik-danismanlik-merkezi-antalya", permanent: true },
      { source: "/:locale/psikolog/trabzon-psikolog-yenibirgun-psikolojik-danismanlik-aile-evlilik-terapisi-yomra", destination: "/:locale/psikolog/trabzon-psikolog", permanent: true },
      { source: "/:locale/psikolog/psikolium-danismanlik-ve-kocluk-merkezi-beylikduzu-psikolog-beylikduzu-pedagog", destination: "/:locale/psikolog/psikolium-danismanlik-ve-kocluk-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/ankara-cocuk-ergen-psikolojik-danismanlik-oyun-terapisi-psk-dan-sila-doganlar", destination: "/:locale/psikolojik-danisman/sila-doganlar-ankara", permanent: true },
      { source: "/:locale/psikolog/kayseri-psikolog-ipek-timur-aile-danismani-cift-terapisi-yetiskin-terapi-emdr", destination: "/:locale/psikolog/ipek-timur-kayseri", permanent: true },
      { source: "/:locale/psikolog/kmaras-marjinal-psikoloji-ergen-yetiskin-bdt-ciftlerle-psikolojik-danismanlik", destination: "/:locale/psikolog/marjinal-psikoloji-ergen-yetiskin-bdt-kahramanmaras", permanent: true },
      { source: "/:locale/psikiyatrist/antalya psikiyatrist-ceyda-guvenc-psikiyatrist-psikoterapist-cinsel-terapist", destination: "/:locale/psikiyatrist/ceyda-guvenc-antalya", permanent: true },
      { source: "/:locale/psikolog/bursada-psikolojik-danismanlik-merkezi-uzman-klinik-psikolog-esra-vatansever", destination: "/:locale/psikolog/esra-vatansever-bursa", permanent: true },
      { source: "/:locale/psikolog/berra-bas-uzman-klinik-psikolog-lisansli-psikoterapist-istanbul-bahcelievler", destination: "/:locale/psikolog/berra-bas-uzman-klinik-psikolog-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/antalya-cocuk-ve-ergen-psikiyatristi-psikoterapist-uzm-dr-gulseren-taskiran", destination: "/:locale/psikiyatrist/gulseren-taskiran-antalya", permanent: true },
      { source: "/:locale/psikolog/mersin-psikolog-aile-danismanligi-cocuk-terapisi-say-psikolojik-danismanlik", destination: "/:locale/psikolog/mersin-psikolog", permanent: true },
      { source: "/:locale/psikolog/kayseri-psikolog-mehmet-tarik-cay-yetiskin-terapi-ergen-terapi-emdr-terapi", destination: "/:locale/psikolog/mehmet-tarik-cay-kayseri", permanent: true },
      { source: "/:locale/psikolog/gaziemir-moneta-psikoloji-cocukergen-yetiskin-psikolog-pedagog-psikoterapi", destination: "/:locale/psikolog/gaziemir-moneta-psikoloji-izmir", permanent: true },
      { source: "/:locale/psikolog/kadikoy-kronos-psikoloji-merkezi-klinik-psikologpsikoterapist-busra-kordag", destination: "/:locale/psikolog/busra-kordag-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/prof-dr-inci-meltem-atay-psikiyatri-psikoterapi-antalya-online-psikoterapi", destination: "/:locale/psikiyatrist/inci-meltem-atay-antalya", permanent: true },
      { source: "/:locale/psikolojik-danisman/kayseri-psikolojik-danisman-resul-adem-sarac-yetiskin-terapi-emdr-terapisi", destination: "/:locale/psikolojik-danisman/resul-adem-sarac-kayseri", permanent: true },
      { source: "/:locale/psikolog/denizli-klinik-psikolog-zehra-akhan-demirel-cocuk-genc-veyetiskin-psikolog", destination: "/:locale/psikolog/zehra-akhan-demirel-denizli", permanent: true },
      { source: "/:locale/psikolog/eskisehir-klinik-psikolog-serhat-uludemir-ozel-saglik-meslek-hizmet-birimi", destination: "/:locale/psikolog/serhat-uludemir-eskisehir", permanent: true },
      { source: "/:locale/psikolog/diyarbakir-psikolog-persona-psikoterapi-egitim-ve-danismanlik-psikoterapi", destination: "/:locale/psikolog/diyarbakir-psikolog", permanent: true },
      { source: "/:locale/psikolog/istanbul-maltepe-cocuk-psikologu-psikomini-psikolojik-danismanlik-merkezi", destination: "/:locale/psikolog/psikomini-psikolojik-danismanlik-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolog/beylikduzu-cift-terapisti-evlilik-terapisti-iliski-terapisti-serhat-damar", destination: "/:locale/psikolog/serhat-damar-istanbul", permanent: true },
      { source: "/:locale/psikolog/beylikduzu-klinik-psikolog-isilay-sarvan-ozel-saglik-meslek-hizmet-birimi", destination: "/:locale/psikolog/isilay-sarvan-istanbul", permanent: true },
      { source: "/:locale/psikolog/bepal-psikoloji-konya-psikolog-aile-ve-cift-terapisi-klnkpskbetul-palanci", destination: "/:locale/psikolog/betul-palanci-konya", permanent: true },
      { source: "/:locale/psikiyatrist/adana-cocuk-psikiyatristi-uzm-dr-atilla-birdir-seyhan-cocuk-psikiyatristi", destination: "/:locale/psikiyatrist/atilla-birdir-adana", permanent: true },
      { source: "/:locale/psikolog/fırat-yalcın-atasehir-aile-ve-cift-danismanligi-uzman-psikolojik-danisman", destination: "/:locale/psikolog/firat-yalcin-istanbul", permanent: true },
      { source: "/:locale/psikolog/go-psikoloji-psk-gulnur-ozdere-konya-aile-danismani-cocuk-ergen-danismani", destination: "/:locale/psikolog/gulnur-ozdere-konya", permanent: true },
      { source: "/:locale/psikolog/tuncay-selek-psikolojik-danismanlik-aile-evlilik-iliski-danismanligi-emdr", destination: "/:locale/psikolog/tuncay-selek-konya", permanent: true },
      { source: "/:locale/psikiyatrist/tms-clinic-istanbul-tms-tedavisi-atasehir-psikiyatrist-atasehir-psikolog", destination: "/:locale/psikiyatrist/tms-clinic-istanbul-istanbul", permanent: true },
      { source: "/:locale/psikolog/umraniye-psikolog-kubra-deniz-umraniye-psikologpsikolog-randevucocuk-psi", destination: "/:locale/psikolog/kubra-deniz-umraniye-psikolog-istanbul", permanent: true },
      { source: "/:locale/psikolog/antalya-uzman-psikolog-ece-altiparmak-bireysel-danismanlik-cift-terapisi", destination: "/:locale/psikolog/ece-altiparmak-antalya", permanent: true },
      { source: "/:locale/psikolog/suzan-aksoy-odak-psikolojik-danismanlik-antalya-psikolog-antalya-pedagog", destination: "/:locale/psikolog/odak-psikolojik-danismanlik-antalya-psikolog-antalya", permanent: true },
      { source: "/:locale/psikolog/eskisehir-klinik-psikolog-salih-eskici-ozel-serbest-meslek-hizmet-birimi", destination: "/:locale/psikolog/salih-eskici-eskisehir", permanent: true },
      { source: "/:locale/psikolog/hacettepeliler-psikoloji-klinik-psikolog-bahattin-bakir-mersin-psikoloji", destination: "/:locale/psikolog/bahattin-bakir-mersin", permanent: true },
      { source: "/:locale/psikolog/hiera-psikoloji-denizli-psikolog-denizli-aile-danismani-denizli-pedagog", destination: "/:locale/psikolog/hiera-psikoloji-denizli", permanent: true },
      { source: "/:locale/psikolog/bursa-klinik-psk-neyran-degirmenci-ceribas-oyun-terapi-cocuk-ergen-aile", destination: "/:locale/psikolog/neyran-degirmenci-ceribas-bursa", permanent: true },
      { source: "/:locale/psikolog/kuta-yasam-merkezi-mersin-psikolog-mersin-fizyoterapi-mersin-diyetisyen", destination: "/:locale/psikolog/kuta-yasam-merkezi-mersin-psikolog", permanent: true },
      { source: "/:locale/psikolog/busra-aygunduz-emdr-terapisi-bdt-cift-ve-aile-terapisi-kadikoy-psikolog", destination: "/:locale/psikolog/busra-aygunduz-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/gaziantep-psikiyatrist-hasan-bayar-cocuk-ergen-psikiyatri-muayanehanesi", destination: "/:locale/psikiyatrist/hasan-bayar-gaziantep", permanent: true },
      { source: "/:locale/psikolog/sakarya-psikolog-uzmklinik-pskhamza-say-ve-uzm-klinik-psikolog-sena-say", destination: "/:locale/psikolog/hamza-say-sakarya", permanent: true },
      { source: "/:locale/psikiyatrist/doc-dr-cilem-bilginer-trabzon-cocuk-ve-ergen-psikiyatrisi-psikoterapist", destination: "/:locale/psikiyatrist/cilem-bilginer-trabzon", permanent: true },
      { source: "/:locale/psikolog/istanbul-pendik-aile-cocuk-terapsi-ozel-gunes-aile-danismanlik-merkezi", destination: "/:locale/psikolog/ozel-gunes-aile-danismanlik-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolog/pinar-aygunduz-emdr-bdt-cbt-cift-ve-aile-danismanligi-kadikoy-psikolog", destination: "/:locale/psikolog/pinar-aygunduz-istanbul", permanent: true },
      { source: "/:locale/psikolog/psk-klinik-mersin-psikolog-psikolojik-danismanlik-aile-danisma-merkezi", destination: "/:locale/psikolog/psk-klinik-mersin-psikolog-psikolojik-danismanlik-mersin", permanent: true },
      { source: "/:locale/psikolog/bursa-psikolog-klinik-psikolog-sahin-ucar-cinsel-terapi-ve-hipnoterapi", destination: "/:locale/psikolog/sahin-ucar-bursa", permanent: true },
      { source: "/:locale/psikolog/merve-kayki-polatli-psikolog-yetiskin-psikolog-cocuk-ve-ergen-psikolog", destination: "/:locale/psikolog/merve-kayki-ankara", permanent: true },
      { source: "/:locale/psikolojik-danisman/selma-akbulut-therapium-psikolojik-danismanlik-merkezi-sated-psikoloji", destination: "/:locale/psikolojik-danisman/selma-akbulut-antalya", permanent: true },
      { source: "/:locale/psikolojik-danisman/antalya-aile-ve-cift-terapisti-antalya-psikoterapist-havva-burcu-aydin", destination: "/:locale/psikolojik-danisman/havva-burcu-aydin-antalya", permanent: true },
      { source: "/:locale/psikolog/irem-bulut-feneryolu-psikolog-klinik-psikolog-kadikoy-psikolog-onerisi", destination: "/:locale/psikolog/irem-bulut-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/doc-dr-ismail-volkan-sahiner-sahiner-psikiyatri-ve-psikoterapi-merkezi", destination: "/:locale/psikiyatrist/doc-dr-ismail-volkan-sahiner-sahiner-psikiyatri-ankara", permanent: true },
      { source: "/:locale/psikolojik-danisman/beylikduzu-cucuk-psikolog-lina-cocuk-ergen-aile-egitim-ve-danismanlik", destination: "/:locale/psikolojik-danisman/lina-cocuk-ergen-aile-egitim-ve-danismanlik-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/ankara-psikiyatri-drarzu-hisarvant-psikiyatri-merkezi-ankara-psikolog", destination: "/:locale/psikiyatrist/ankara-psikiyatri-dr-arzu-hisarvant", permanent: true },
      { source: "/:locale/psikolog/bostanci-psikolog-salih-fatih-demir-goztepe-psikolog-kadikoy-psikolog", destination: "/:locale/psikolog/salih-fatih-demir-istanbul", permanent: true },
      { source: "/:locale/psikolog/bostanli-psikoloji-ve-psikodrama-merkezi-izmir-psikolog-online-terapi", destination: "/:locale/psikolog/bostanli-psikoloji-ve-psikodrama-merkezi-izmir", permanent: true },
      { source: "/:locale/psikolog/istanbul-maltepe-aile-danışmanı-ozel-victor-aile-danismanlik-merkezi", destination: "/:locale/psikolog/ozel-victor-aile-danismanlik-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolog/adana-vajinismus-tedavi-merkezi-pskcinsel-terapist-elif-dogan-sungur", destination: "/:locale/psikolog/elif-dogan-sungur-adana", permanent: true },
      { source: "/:locale/psikolog/baris-enens-arikan-pax-psikoloji-antalya-psikolog-muratpasa-psikolog", destination: "/:locale/psikolog/baris-enes-arikan-antalya", permanent: true },
      { source: "/:locale/psikolog/umran-yelekin-psikoloji-klinigi-cocuk-ve-genc-psikologu-berfin-bicer", destination: "/:locale/psikolog/berfin-bicer-gaziantep", permanent: true },
      { source: "/:locale/psikolog/rohat-bahtiyar-i-ozel-saglik-meslek-hizmet-birimi-i-sakarya-psikolog", destination: "/:locale/psikolog/rohat-bahtiyar-sakarya", permanent: true },
      { source: "/:locale/psikolog/ozel-saglik-meslek-hizmet-birimi-uzm-klinik-psikolog-zeynep-alanyali", destination: "/:locale/psikolog/zeynep-alanyali-izmir", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-drzeynep-esenkaya-usta-cocuk-ve-genc-psikiyatristi-psikoterapist", destination: "/:locale/psikiyatrist/zeynep-esenkaya-usta-konya", permanent: true },
      { source: "/:locale/psikiyatrist/pdr-merkezi-kayseri-psikolog-psikolojik-danisma-ve-rehberlik-merkezi", destination: "/:locale/psikiyatrist/pdr-merkezi-kayseri", permanent: true },
      { source: "/:locale/psikiyatrist/nuray-er-izmir-psikolog-aile-danismani-cift-terapisti-emdr-terapisti", destination: "/:locale/psikiyatrist/nuray-er-izmir", permanent: true },
      { source: "/:locale/psikiyatrist/doc-dr-yalcin-guzelhan-psikiyatrist-psikoterapist-sinirbilim-uzmani", destination: "/:locale/psikiyatrist/yalcin-guzelhan-psikiyatrist-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/can-psikolojik-danismanlik-merkezi-ankara-psikolog-cocuk-psikiyatri", destination: "/:locale/psikiyatrist/can-psikolojik-danismanlik-merkezi-ankara", permanent: true },
      { source: "/:locale/psikolog/uzman-cocuk-ve-ergen-psikolojisi-pedagog-deniz akıncı-klinigi-konya", destination: "/:locale/psikolog/deniz-akinci-konya", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-emrah-yildiz-gaziantep-tms-psikiyatri-ve-psikoterapi-klinigi", destination: "/:locale/psikiyatrist/emrah-yildiz-gaziantep", permanent: true },
      { source: "/:locale/psikolog/adana-bagimlilik-psikologu-phd-uzman-klinik-psikolog-emre-altinkurt", destination: "/:locale/psikolog/phd-uzman-klinik-psikolog-emre-altinkurt-adana", permanent: true },
      { source: "/:locale/psikolog/uzm-psikolojik-danisman-omer-akturk-mavi-agac-psikoloji-danismanlik", destination: "/:locale/psikolog/omer-akturk-bursa", permanent: true },
      { source: "/:locale/psikolog/beril-zeynep-haciosman-uzman-klinik-psikolog-psiko-koza-danismanlik", destination: "/:locale/psikolog/beril-zeynep-haciosman-uzman-klinik-psikolog-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/izmir-psikiyatri-uz-dr-olga-gokbulut-izmir-bayraklida-psikiyatrist", destination: "/:locale/psikiyatrist/olga-gokbulut-izmir", permanent: true },
      { source: "/:locale/psikolog/lotus-psikolojik-danismanlik-merkezi-uzman-psikolog-nurgul-bahadir", destination: "/:locale/psikolog/nurgul-bahadir-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/mk-psikolojik-danismanlik-merkezi-cankaya-psikolog-melis-karakaya", destination: "/:locale/psikolojik-danisman/melis-karakaya-ankara", permanent: true },
      { source: "/:locale/psikolog/gunaydin-psikolojik-danismanlikuzm-klinik-psikolog-gokce-gunaydin", destination: "/:locale/psikolog/gokce-gunaydin-istanbul", permanent: true },
      { source: "/:locale/psikolog/aile-terapisti-izmir-uzman-evlilik-cift-danismanligi-ay-psikoloji", destination: "/:locale/psikolog/ay-psikoloji-izmir", permanent: true },
      { source: "/:locale/psikolog/etimesgut-eryaman-dilem-psikolojik-danismanlik-merkezi-sule-sahin", destination: "/:locale/psikolog/sule-sahin-ankara", permanent: true },
      { source: "/:locale/psikolog/aliye-kut-online-psikolog-izmir-bayrakli-psikolog-cocuk-psikologu", destination: "/:locale/psikolog/aliye-kut-izmir", permanent: true },
      { source: "/:locale/psikolog/uzman-klinik-psikolog-aile-danismani-ve-cift-terapisti-esra-sayin", destination: "/:locale/psikolog/esra-sayin-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/aile-danismanligi-evlilik-cift-terapisi-gaziantep-aile-danısmanı", destination: "/:locale/psikolojik-danisman/aile-dan-okan-bal-gaziantep", permanent: true },
      { source: "/:locale/psikolog/kadikoy-klinik-psikolog-caddebostan-psikoterapist-ela-nur-ruzgar", destination: "/:locale/psikolog/ela-nur-ruzgar-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/merve-ari-bireysel-danismanlik-ergen-danismanligi-emdr-terapisti", destination: "/:locale/psikiyatrist/merve-ari-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-nurten-gozde-kamar-izmir-cocuk-ve-ergen-psikiyatri-uzmani", destination: "/:locale/psikiyatrist/nurten-gozde-kamar-izmir", permanent: true },
      { source: "/:locale/psikolog/dsm-psikoloji-kayseri-psikolog-kayseri-psikoloji-kayseri-pedagog", destination: "/:locale/psikolog/dsm-psikoloji-kayseri", permanent: true },
      { source: "/:locale/psikiyatrist/gizem-erbas-kayseri-psikolog-kayseri-emdr-kayseri-oyun-terapisi-", destination: "/:locale/psikiyatrist/gizem-erbas-kayseri", permanent: true },
      { source: "/:locale/psikolog/bilge-psikoloji-oyun-terapisi-cocuk-ergen-yetiskin-cift-terapisi", destination: "/:locale/psikolog/bilge-psikoloji-oyun-terapisi-cocuk-ergen-yetiskin-ankara", permanent: true },
      { source: "/:locale/psikolog/berat-hazar-kayseri-psikolog-yetiskin-psikolojisi-emdr-terapisti", destination: "/:locale/psikolog/berat-haza-kayseri", permanent: true },
      { source: "/:locale/psikolog/uzm-klinik-psikolog-sonay-aksungur-emdr-avrupa-akredite-terapist", destination: "/:locale/psikolog/sonay-aksungur-istanbul", permanent: true },
      { source: "/:locale/psikolog/kadikoy-dunya-danismanlik-ve-psikoloji-merkezi-kadikoy-psikolog", destination: "/:locale/psikolog/kadikoy-dunya-danismanlik-ve-psikoloji-merkezi-istanbul", permanent: true },
      { source: "/:locale/psikolog/pursaklar-psikolog-umut-psikoloji-egitim-ve-psikoterapi-merkezi", destination: "/:locale/psikolog/umut-psikoloji-egitim-ve-psikoterapi-merkezi-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/mustafa-can-erkan-antalya-cocuk-ve-genc-psikiyatristi-koyaaltı", destination: "/:locale/psikiyatrist/mustafa-can-erkan-antalya", permanent: true },
      { source: "/:locale/psikolog/ozel-saglik-meslek-hizmet-birimi-klinik-psikolog-nurcan-toprak", destination: "/:locale/psikolog/nurcan-toprak-mersin", permanent: true },
      { source: "/:locale/psikolog/sinar-psikolojik-danismanlik-merkezi-gaziemir-psikolog-pedagog", destination: "/:locale/psikolog/sinar-psikolojik-danismanlik-merkez-izmir", permanent: true },
      { source: "/:locale/psikolog/mersin-psikolog-mersin-psikolojik-danismanlik-yasam-psikoloji", destination: "/:locale/psikolog/mersin-psikolog-mersin-2", permanent: true },
      { source: "/:locale/psikiyatrist/mustafa-kemal-ozcan-yetiskin-ve-cocuk-ergen-psikiyatri-uzmani", destination: "/:locale/psikiyatrist/mustafa-kemal-ozcan-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/prof-dr-cebrail-kisa-ankara-psikiyatri-ve-psikoterapi-merkezi", destination: "/:locale/psikiyatrist/cebrail-kisa-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-deniz-karayun-muayenehanesi-psikiyatrist-psikoterapist", destination: "/:locale/psikiyatrist/deniz-karayun-adana", permanent: true },
      { source: "/:locale/psikolojik-danisman/van-psikolog-ela-ozcanli-karakoc-sema-psikoloji-van-psikoloji", destination: "/:locale/psikolojik-danisman/ela-ozcanli-karakoc-van", permanent: true },
      { source: "/:locale/psikolog/can-yilmaz-kadikoy-bagdat-caddesi-caddebostan-klinik-psikolog", destination: "/:locale/psikolog/can-yilmaz-istanbul", permanent: true },
      { source: "/:locale/psikolog/gaziantep-psikolog-leyla-colak-kaya-gaziantep-klinik-psikolog", destination: "/:locale/psikolog/leyla-colak-kaya-gaziantep", permanent: true },
      { source: "/:locale/psikolog/yesim-ayyildiz-cekmekoyumraniye-psikolog-cocuk-ergen-psikolog", destination: "/:locale/psikolog/yesim-ayyildiz-istanbul", permanent: true },
      { source: "/:locale/psikolog/ena-therapia-psikoterapi-uzmklinik-psikolog-esin-nur-akyildiz", destination: "/:locale/psikolog/esin-nur-akyildiz-istanbul", permanent: true },
      { source: "/:locale/psikolog/oyun-terapisi-merkezi-istanbul-psikolog-sirma-gul-ozkur-", destination: "/:locale/psikolog/sirma-gul-ozkur-istanbul", permanent: true },
      { source: "/:locale/psikolog/izmir-pedagog-oyun-terapisti-psikolog-nigar-banu-kina-", destination: "/:locale/psikolog/nigar-banu-kina-izmir", permanent: true },
      { source: "/:locale/psikolog/istanbul--beylikduzu-psikolog-emine-lamiser-atik", destination: "/:locale/psikolog/emine-lamiser-atik-istanbul", permanent: true },
      { source: "/:locale/psikolog/istanbul-maltepe-kliniik-psikolog-beril-ceylan-", destination: "/:locale/psikolog/beril-ceylan-istanbul", permanent: true },
      { source: "/:locale/psikolog/ayse-esra-karakaya-kayseri-psikolog-kocasinan-", destination: "/:locale/psikolog/ayse-esra-karakaya-kayseri", permanent: true },
      { source: "/:locale/psikolog/adana-cukurova-psikolog-nazlican-toklu-yildiz-", destination: "/:locale/psikolog/nazlican-toklu-yildiz-adana", permanent: true },
      { source: "/:locale/psikolog/bursa-psikolog--nilüfer-psikolog-tugba-yasar", destination: "/:locale/psikolog/tugba-yasar-bursa", permanent: true },
      { source: "/:locale/psikiyatrist/-gaziantep-psikiyatrist-doktor-mustafa-celik", destination: "/:locale/psikiyatrist/mustafa-celik-gaziantep", permanent: true },
      { source: "/:locale/psikolojik-danisman/antalya-pedagog-uzman-psikolojik-danisman-", destination: "/:locale/psikolojik-danisman/s-nur-kurtulus-kahyalar-antalya", permanent: true },
      { source: "/:locale/psikolog/-insanlik-hali-psikoloji-konya-psikolog-", destination: "/:locale/psikolog/selcuk-duman-konya", permanent: true },
      { source: "/:locale/psikiyatrist/kayseri-psikiyatrist-uzm-dr-tugba-kara-", destination: "/:locale/psikiyatrist/tugba-kara-kayseri", permanent: true },
      { source: "/:locale/psikolog/frezya-psikoloji-sancaktepe-psikolog-", destination: "/:locale/psikolog/frezya-psikoloji-istanbul", permanent: true },
      { source: "/:locale/psikolog/-psikolog-gaziantep-yunus-emre-seker", destination: "/:locale/psikolog/yunus-emre-seker-gaziantep", permanent: true },
      { source: "/:locale/psikolog/esenyurt-psikolog-lotusta-psikoloji-", destination: "/:locale/psikolog/lotusta-psikoloji-istanbul", permanent: true },
      { source: "/:locale/psikolojik-danisman/antalya-danisman-yesim-yavuz-uysal-", destination: "/:locale/psikolojik-danisman/yesim-yavuz-uysal-antalya", permanent: true },
      { source: "/:locale/psikiyatrist/-uzm-dr-halide-tuysuzogullari-bursa", destination: "/:locale/psikiyatrist/halide-tuysuzogullari-bursa", permanent: true },
      { source: "/:locale/psikolog/sena-sumur-ankara-klinik-psikolog-", destination: "/:locale/psikolog/sena-sumur-ankara", permanent: true },
      { source: "/:locale/psikolog/-tekirdag-psk-melisa-aleyna-ciftci", destination: "/:locale/psikolog/melisa-aleyna-ciftci-tekirdag", permanent: true },
      { source: "/:locale/psikolog/esenyurt-psikolog-oznur-karabas-", destination: "/:locale/psikolog/oznur-karabas-istanbul", permanent: true },
      { source: "/:locale/psikiyatrist/psikiyatrist-dr-bulent-celikel-", destination: "/:locale/psikiyatrist/bulent-celikel-ankara", permanent: true },
      { source: "/:locale/psikolog/-bursa-psikolog-yasemin-gorecek", destination: "/:locale/psikolog/yasemin-gorecek-bursa", permanent: true },
      { source: "/:locale/psikolog/cansu-aydin-ankara-psikolog-", destination: "/:locale/psikolog/cansu-aydin-ankara", permanent: true },
      { source: "/:locale/psikiyatrist/uzm-dr-aysel-alkan-koseoglu-", destination: "/:locale/psikiyatrist/aysel-alkan-koseoglu-bursa", permanent: true },
      // /tr/therapists/ → /tr/terapistler/ (SEO)
      { source: "/tr/therapists", destination: "/tr/terapistler", permanent: true },
      { source: "/tr/therapists/:path*", destination: "/tr/terapistler/:path*", permanent: true },
      // EN içerik tamamen kaldırıldı — Terapimap yalnızca TR pazarına hizmet ediyor.
      // /en/therapists/... önce TR eşdeğerine (terapistler) haritalanıyor, sonra genel
      // /en/:path* kuralı kalan tüm sayfaları (profil, rehber, statik sayfalar) TR'ye taşıyor.
      { source: "/en/therapists", destination: "/tr/terapistler", permanent: true },
      { source: "/en/therapists/:path*", destination: "/tr/terapistler/:path*", permanent: true },
      { source: "/en", destination: "/tr", permanent: true },
      { source: "/en/:path*", destination: "/tr/:path*", permanent: true },
    ];
  },
  async rewrites() {
    return [
      // /terapistler/ isteğini içeride /therapists/ route'una yönlendir
      { source: "/:locale/terapistler", destination: "/:locale/therapists" },
      { source: "/:locale/terapistler/:path*", destination: "/:locale/therapists/:path*" },
    ];
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "avatars.githubusercontent.com" },
      { protocol: "https", hostname: "ozsqrekaugyvodmajxqr.supabase.co" },
    ],
  },
};

export default withNextIntl(nextConfig);
